Pre-trainingDatasetPath:
- BTCV
- TCIAcovid19
- Luna16-jx
- stoic21
- Totalsegmentator_dataset
- Flare23
- LIDC_convert_v1
- OPC_convert_v1
- TCGA-HNSC_convert_v1
- QIN_convert_v1
- HNPC_convert_v1
- HNSCC_convert_v1
- CT_COLONOGRAPHY_converted_v1
- StonyBrookChestCT_v1
- NLST_convert_v1
Pre-trainingDatasetJson:
- btcv.json
- dataset_TCIAcovid19_0.json
- dataset_LUNA16_0.json
- stoic21.json
- Totalsegmentator_dataset.json
- flare23.json
- LIDC.json
- OPCRadiomics.json
- TCGA_HNSC.json
- QIN_HeadNeck.json
- HeadNeckPet.json
- HNSCC.json
- ColonographyTrials.json
- StonyBrookChestCT.json
- NLST_convert_v1.json
DatasetSplit:
    1k:
    - BTCV
    - TCIAcovid19
    +2k:
    - Luna16-jx
    +4k:
    - stoic21
    +10k:
    - Totalsegmentator_dataset
    - Flare23
    - HNSCC_convert_v1
    +20k:
    - OPC_convert_v1
    - TCGA-HNSC_convert_v1
    - QIN_convert_v1
    - HNPC_convert_v1
    - CT_COLONOGRAPHY_converted_v1
    - StonyBrookChestCT_v1
    +100k:
    - NLST_convert_v1
    +110k:
    - Private01
    - Private02