NLST_convert_v1:
- /data/CT/data/NLST_convert_v1/115572.nii.gz
- /data/CT/data/NLST_convert_v1/115882.nii.gz
- /data/CT/data/NLST_convert_v1/115884.nii.gz
- /data/CT/data/NLST_convert_v1/115885.nii.gz
- /data/CT/data/NLST_convert_v1/115887.nii.gz
- /data/CT/data/NLST_convert_v1/115888.nii.gz
